<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VJ-ThinkVersion" failures="2" tests="2" name="Test" time="19.561" errors="0" timestamp="2022-05-25T23:30:36 IST">
  <testcase classname="sampmaven.LoginModuleTest" name="ForgetPassword" time="4.251">
    <failure type="java.lang.AssertionError" message="expected [Login Name not found in the .] but found [Login Name not found in the system.]">
      <![CDATA[java.lang.AssertionError: expected [Login Name not found in the .] but found [Login Name not found in the system.]
at sampmaven.LoginModuleTest.ForgetPassword(LoginModuleTest.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ForgetPassword -->
  <testcase classname="sampmaven.LoginModuleTest" name="SuccessfullLogin" time="1.128">
    <failure type="java.lang.AssertionError" message="expected [Login incorrect. Please try ] but found [Login incorrect. Please try again]">
      <![CDATA[java.lang.AssertionError: expected [Login incorrect. Please try ] but found [Login incorrect. Please try again]
at sampmaven.LoginModuleTest.SuccessfullLogin(LoginModuleTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- SuccessfullLogin -->
</testsuite> <!-- Test -->
